export const DISPATCH_TO_STORE = 'DISPATCH_TO_STORE';

export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const UPDATE_SCREEN_TYPE = 'UPDATE_SCREEN_TYPE';
export const UPDATE_LANGUAGE = 'UPDATE_LANGUAGE';
export const UPDATE_PHONE_NUMS = 'UPDATE_PHONE_NUMS';
export const UPDATE_PHONE_OPTIONS = 'UPDATE_PHONE_OPTIONS';
export const UPDATE_MENU = 'UPDATE_MENU';
export const UPDATE_MODIFICATIONS = 'UPDATE_MODIFICATIONS';
export const UPDATE_ADDRESSES = 'UPDATE_ADDRESSES';
export const UPDATE_ADDRESS_OPTIONS = 'UPDATE_ADDRESS_OPTIONS';
export const UPDATE_CUSTOMER_INFO = 'UPDATE_CUSTOMER_INFO';
export const UPDATE_FOCUSED_SECTION = 'UPDATE_FOCUSED_SECTION';
export const UPDATE_FOCUSED_ITEMS = 'UPDATE_FOCUSED_ITEMS';
export const UPDATE_ITEMS = 'UPDATE_ITEMS';
export const UPDATE_ORDERLIST_INFO = 'UPDATE_ORDERLIST_INFO';
// export const UPDATE_ITEM_MODIFICATION = 'UPDATE_ITEM_MODIFICATION';
// export const UPDATE_CURRENT_BIANG = 'UPDATE_CURRENT_BIANG';

// export const ADD_ITEM = 'ADD_ITEM';