export const DISPATCH_TO_STORE = 'DISPATCH_TO_STORE';
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const UPDATE_SCREEN_TYPE = 'UPDATE_SCREEN_TYPE';
export const UPDATE_LANGUAGE = 'UPDATE_LANGUAGE';
export const UPDATE_PHONE_NUMS = 'UPDATE_PHONE_NUMS';
export const UPDATE_MENU = 'UPDATE_MENU';